### ISSUE TITLE
It is not working wiht React 18

### ISSUE THREAD

**Issue by shubhambatra** [onderonur/react-infinite-scroll-hook#34] opened 2023-01-24 12:51 UTC
I have upgraded my project from react 17 to react 18.
also upgraded the react-infinite-scroll-hook 4.01 to 4.04. but it is not working.

**Comment by onderonur** [comment] 2023-01-25 00:44
Hello there 👋 
Can you provide a reproduction of the issue please?
There was an issue about `useEffect` running twice in React 18 when `StrictMode` on. But it's fixed with `v4.0.3`.
And I have 2 repositories (one with Next.js, one with Remix) which are using React 18 with this package and there are no problems in them. So, a reproduction may help us find the problem.
Thanks 🙏 

Next.js project: https://github.com/onderonur/tmdb-explorer
Remix project: https://github.com/onderonur/remix-shows

**Comment by onderonur** [comment] 2024-08-17 23:24
Closing this issue since there is not much activity for this one 👍

**Closed as completed by onderonur** 2024-08-17 23:24 UTC
